# Generated by Django 4.0.6 on 2024-11-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('google_map_url', models.URLField(max_length=500)),
                ('photo', models.ImageField(upload_to='portfolio_photos/')),
            ],
        ),
    ]
