# Generated by Django 4.0.6 on 2024-11-19 23:51

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='portfolio_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio_videos/')),
                ('address', django_google_maps.fields.AddressField(default='Ireland', max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(default='53.3522908033196,-6.257729843109473', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Entries',
                'ordering': ['date'],
            },
        ),
    ]
