# Generated by Django 4.0.6 on 2024-11-20 01:35

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, default='53.3522908033196,-6.257729843109473', max_length=100),
        ),
    ]
