# Generated by Django 4.0.6 on 2024-11-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioentry',
            name='google_map_url',
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='google_map_embed',
            field=models.TextField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3021.944474126218!2d-73.97418748430235!3d40.78509137932583!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c2589b799c2955%3A0x4539316fa1c8c802!2sCentral%20Park!5e0!3m2!1sen!2sus!4v1731986174943!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'),
        ),
    ]
