# Generated by Django 4.0.6 on 2024-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolioentry_google_map_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_videos/'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='google_map_embed',
            field=models.TextField(default='<iframe src="https://www.google.com/maps/embed?..."></iframe>'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_photos/'),
        ),
    ]
